Add MS segmentation Basel
neuropoly/data-management pull request #125
Opened 2021-09-22 20:07 UTC by alexfoias

We have received more data. We have to add them in our git repo basel-mp2rage

I have added the data under datasets/basel-mp2rage/ on the branch af/add_data_katrin

Log here: 

```
git log --stat master..HEAD
commit 88c506eb9855d6a0cb29a2e95c3283b8fd0a8099 (HEAD -> af/add_data_katrin, origin/af/add_data_katrin)
Author: Alexandru Foias <afoias@polymtl.ca>
Date:   Wed Sep 22 15:57:50 2021 -0400

    add les manual data

 derivatives/labels/sub-P001/anat/sub-P001_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P001/anat/sub-P001_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P002/anat/sub-P002_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P002/anat/sub-P002_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P003/anat/sub-P003_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P003/anat/sub-P003_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P004/anat/sub-P004_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P004/anat/sub-P004_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P005/anat/sub-P005_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P005/anat/sub-P005_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P006/anat/sub-P006_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P006/anat/sub-P006_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P007/anat/sub-P007_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P007/anat/sub-P007_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P010/anat/sub-P010_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P010/anat/sub-P010_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P011/anat/sub-P011_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P011/anat/sub-P011_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P012/anat/sub-P012_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P012/anat/sub-P012_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P013/anat/sub-P013_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P013/anat/sub-P013_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P014/anat/sub-P014_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P014/anat/sub-P014_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P015/anat/sub-P015_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P015/anat/sub-P015_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P016/anat/sub-P016_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P016/anat/sub-P016_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P017/anat/sub-P017_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P017/anat/sub-P017_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P019/anat/sub-P019_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P019/anat/sub-P019_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P021/anat/sub-P021_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P021/anat/sub-P021_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P022/anat/sub-P022_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P022/anat/sub-P022_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P023/anat/sub-P023_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P023/anat/sub-P023_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P024/anat/sub-P024_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P024/anat/sub-P024_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P025/anat/sub-P025_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P025/anat/sub-P025_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P026/anat/sub-P026_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P026/anat/sub-P026_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P027/anat/sub-P027_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P027/anat/sub-P027_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P028/anat/sub-P028_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P028/anat/sub-P028_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P029/anat/sub-P029_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P029/anat/sub-P029_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P030/anat/sub-P030_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P030/anat/sub-P030_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P031/anat/sub-P031_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P031/anat/sub-P031_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P033/anat/sub-P033_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P033/anat/sub-P033_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P034/anat/sub-P034_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P034/anat/sub-P034_UNIT1_lesion-manual2.nii.gz | 1 +
 derivatives/labels/sub-P035/anat/sub-P035_UNIT1_lesion-manual2.json   | 4 ++++
 derivatives/labels/sub-P035/anat/sub-P035_UNIT1_lesion-manual2.nii.gz | 1 +
 60 files changed, 150 insertions(+)
```

2021-09-23 00:52 UTC, jcohenadad commented on scripts/HCI_test.sh
> +#!/bin/bash
what's this file?

2021-09-23 00:57 UTC, jcohenadad approved these changes
i reviewed the git annex data-- LGTM!

just the weird unrelated file...

2021-09-23 13:03 UTC, alexfoias commented
Fixed it.

2021-09-26 23:29 UTC, kousu commented on scripts/curate_basel_additional_data.py
> +                        data_json_label[u'Label'] = "lesion-manual2"
```suggestion
                        data_json_label['Author'] = "Katrin"
                        data_json_label['Label'] = "lesion-manual2"
```

python3 doesn't need the `u`s

2021-09-26 23:30 UTC, kousu commented on scripts/curate_basel_additional_data.py
> +        shutil.rmtree(path_output)
This line was probably very helpful for development, but I worry about leaving it in. What if someone accidentally runs this script and it erases their entire home folder?

2021-09-26 23:30 UTC, kousu commented on scripts/curate_basel_additional_data.py
> +    input_files.sort()
This is a bit easier

```suggestion
    input_files = sorted(os.listdir(path_input))
```

2021-09-26 23:31 UTC, kousu commented on scripts/curate_basel_additional_data.py
> +            os.makedirs(path_subid_bids_dir_out)
A bit more idiomatic:

```suggestion
        os.makedirs(path_subid_bids_dir_out, exist_ok=True)
```

2021-09-26 23:35 UTC, kousu commented on scripts/curate_basel_additional_data.py
> +        shutil.rmtree(path_output)
In fact, if you ran this on the pre-existing git repo, how did it avoid just wiping out all the pre-existing data? Did you curate it *then* do an extra step where you copied the curated files into the git repo?

2021-09-26 23:39 UTC, kousu commented on scripts/curate_basel_additional_data.py
> +
Personally, I could use a docstring here mentioning the upstream source of the data this script is meant to be run on and/or it's intermediate location on `duke` (if it has one).

2021-09-26 23:41 UTC, kousu commented on scripts/curate_basel_additional_data.py
> +                    if file.endswith('lesion-manual2.nii.gz'):
Is `manual2` a BIDS-compliant datatype?

2021-09-26 23:41 UTC, kousu requested changes
I think the script is missing some context. I know it's just really meant to be used one time so investing in its reliability isn't really worth it, but it would be nice to know we could run it a second or third time when more data comes in and 

a. know what to run it on
b. know it will non-destructively add to the pre-existing git repo

2021-09-28 19:39 UTC, jcohenadad commented
the way i would review this PR:
- check if all files are indeed uploaded
- check the content of a few NIfTI files (there should be binary masks)
- check the content of a few JSON (there should be the name of the radiologist)

2021-12-03 19:46 UTC, jcohenadad commented
@alexfoias is there anything left to do on this branch?

2021-12-03 19:51 UTC, alexfoias commented
No, not as far as I remember. The data is already pushed on the branch.

2021-12-03 20:00 UTC, jcohenadad commented
> No, not as far as I remember. The data is already pushed on the branch. It just has to be merged on the internal repo.

is there a reason the branch still exists? is there a protocol to remove the branches once they are merged? or maybe there is a good reason to keep these branches? (i would vote to remove them to remove confusion)

2021-12-03 20:31 UTC, alexfoias commented
The branch was created to add the script used to curate the data. We have this type of scripts under `scripts/`. In addition, I think here is the only place where we can track what changes we do on the local git server. Unless @jcohenadad or @kousu have suggestions where to discuss about these data curation/addition requests.

2021-12-03 20:43 UTC, jcohenadad commented
> The branch was created to add the script used to curate the data. We have this type of scripts under `scripts/`. 

ah, i see. I didn't realize that this PR is about adding a script in this GH repository directly (i thought that was only about updating the git-annex internal dataset). 

> In addition, I think here is the only place where we can track what changes we do on the local git server. Unless @jcohenadad or @kousu have suggestions where to discuss about these data curation/addition requests.

Indeed, although there are also the message commits that contain information, although it does not provide easy discussion.

I see that @kousu requested changes-- have you implemented them?

2021-12-03 23:15 UTC, kousu commented
The curation script can be kept [under `code/`](https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#code) in the dataset it created. I think BIDS is wise on this point.

2021-12-06 19:08 UTC, alexfoias commented
@kousu https://github.com/neuropoly/data-management/pull/125#discussion_r716280928 these are derivatives, which are not covered by bids specs.

2021-12-06 19:55 UTC, jcohenadad commented
IIUC @kousu 's suggestion was to create a 'scripts/' folder in the database, not in this repository

2021-12-10 17:49 UTC, jcohenadad commented
> IIUC @kousu 's suggestion was to create a 'scripts/' folder in the database, not in this repository

@alexfoias just checking if you saw my message

2021-12-10 18:03 UTC, alexfoias commented
@jcohenadad I have pushed the scripts (`curate_basel.py` and `curate_basel_additional_data.py`) to `datasets/basel-mp2rage/` on the branch `af/add_data_katrin` under `scripts/`. I will remove the files from this repo and then we can close the PR.

2021-12-10 18:11 UTC, alexfoias commented
We can close this PR.

2021-12-10 18:45 UTC, jcohenadad commented
> We can close this PR.

let me just verify that everything is in there, and then i'll give you the OK to merge

2021-12-10 18:47 UTC, jcohenadad commented
looks good 👌 

<details><summary>Terminal output</summary>

```console
julien-macbook:~/data.neuro/basel-mp2rage $ git checkout af/add_data_katrin
Switched to branch 'af/add_data_katrin'
Your branch is up to date with 'origin/af/add_data_katrin'.
julien-macbook:~/data.neuro/basel-mp2rage $ gl
88c506eb9855d6a0cb29a2e95c3283b8fd0a8099 (HEAD -> af/add_data_katrin, origin/synced/af/add_data_katrin, origin/af/add_data_katrin, synced/af/add_data_katrin) add les manual data
11ca3db041edcbed68f8da2c7ced5c08191d3aa8 Initial data
bbe64a383ee28bed150b0018ec9031c040fe71da Configure git-annex
julien-macbook:~/data.neuro/basel-mp2rage $ git pull
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 31 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (31/31), done.
From data.neuro.polymtl.ca:datasets/basel-mp2rage
   88c506e..04b78bb  af/add_data_katrin -> origin/af/add_data_katrin
   80adc00..3ef32cc  git-annex          -> origin/git-annex
Updating 88c506e..04b78bb
Fast-forward
 scripts/curate_basel.py                 | 120 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 scripts/curate_basel_additional_data.py |  53 ++++++++++++++++++++++++++++++++++++++
 2 files changed, 173 insertions(+)
 create mode 100644 scripts/curate_basel.py
 create mode 100644 scripts/curate_basel_additional_data.py
julien-macbook:~/data.neuro/basel-mp2rage $ ll
total 48
drwxr-xr-x  41 julien  staff  1312 10 Dec 13:46 .
drwxr-xr-x  11 julien  staff   352 22 Oct 11:46 ..
drwxr-xr-x  16 julien  staff   512 10 Dec 13:46 .git
-rw-r--r--   1 julien  staff    96 28 Jun 17:08 .gitattributes
-rw-r--r--   1 julien  staff    10 28 Jun 17:08 .gitignore
-rw-r--r--   1 julien  staff   361 28 Jun 17:08 README
-rw-r--r--   1 julien  staff    64 28 Jun 17:08 dataset_description.json
drwxr-xr-x   3 julien  staff    96 10 Dec 12:44 derivatives
-rw-r--r--   1 julien  staff   296 28 Jun 17:08 participants.json
-rw-r--r--   1 julien  staff   533 28 Jun 17:08 participants.tsv
drwxr-xr-x   4 julien  staff   128 10 Dec 13:46 scripts
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P001
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P002
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P003
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P004
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P005
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P006
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P007
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P010
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P011
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P012
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P013
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P014
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P015
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P016
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P017
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P019
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P021
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P022
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P023
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P024
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P025
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P026
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P027
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P028
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P029
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P030
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P031
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P033
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P034
drwxr-xr-x   3 julien  staff    96 28 Jun 17:08 sub-P035
julien-macbook:~/data.neuro/basel-mp2rage $ ll scripts/
total 24
drwxr-xr-x   4 julien  staff   128 10 Dec 13:46 .
drwxr-xr-x  41 julien  staff  1312 10 Dec 13:46 ..
-rw-r--r--   1 julien  staff  4523 10 Dec 13:46 curate_basel.py
-rw-r--r--   1 julien  staff  2239 10 Dec 13:46 curate_basel_additional_data.py
```

</details>

@alexfoias can you please:
- merge the branch af/add_data_katrin
- add here your Terminal output so we know what was done
- close this PR

Thank you @alexfoias

2021-12-10 19:31 UTC, alexfoias commented
Here is the merge
<Details>
```
 git merge --ff-only af/add_data_katrin
Updating 11ca3db..04b78bb
Fast-forward
 .../labels/sub-P001/anat/sub-P001_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P001/anat/sub-P001_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P002/anat/sub-P002_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P002/anat/sub-P002_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P003/anat/sub-P003_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P003/anat/sub-P003_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P004/anat/sub-P004_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P004/anat/sub-P004_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P005/anat/sub-P005_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P005/anat/sub-P005_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P006/anat/sub-P006_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P006/anat/sub-P006_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P007/anat/sub-P007_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P007/anat/sub-P007_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P010/anat/sub-P010_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P010/anat/sub-P010_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P011/anat/sub-P011_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P011/anat/sub-P011_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P012/anat/sub-P012_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P012/anat/sub-P012_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P013/anat/sub-P013_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P013/anat/sub-P013_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P014/anat/sub-P014_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P014/anat/sub-P014_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P015/anat/sub-P015_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P015/anat/sub-P015_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P016/anat/sub-P016_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P016/anat/sub-P016_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P017/anat/sub-P017_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P017/anat/sub-P017_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P019/anat/sub-P019_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P019/anat/sub-P019_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P021/anat/sub-P021_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P021/anat/sub-P021_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P022/anat/sub-P022_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P022/anat/sub-P022_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P023/anat/sub-P023_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P023/anat/sub-P023_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P024/anat/sub-P024_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P024/anat/sub-P024_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P025/anat/sub-P025_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P025/anat/sub-P025_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P026/anat/sub-P026_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P026/anat/sub-P026_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P027/anat/sub-P027_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P027/anat/sub-P027_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P028/anat/sub-P028_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P028/anat/sub-P028_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P029/anat/sub-P029_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P029/anat/sub-P029_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P030/anat/sub-P030_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P030/anat/sub-P030_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P031/anat/sub-P031_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P031/anat/sub-P031_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P033/anat/sub-P033_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P033/anat/sub-P033_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P034/anat/sub-P034_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P034/anat/sub-P034_UNIT1_lesion-manual2.nii.gz  |   1 +
 .../labels/sub-P035/anat/sub-P035_UNIT1_lesion-manual2.json    |   4 +
 .../labels/sub-P035/anat/sub-P035_UNIT1_lesion-manual2.nii.gz  |   1 +
 scripts/curate_basel.py                                        | 120 +++++++++++++++++++++++++++
 scripts/curate_basel_additional_data.py                        |  53 ++++++++++++
 62 files changed, 323 insertions(+)
 create mode 100644 derivatives/labels/sub-P001/anat/sub-P001_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P001/anat/sub-P001_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P002/anat/sub-P002_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P002/anat/sub-P002_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P003/anat/sub-P003_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P003/anat/sub-P003_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P004/anat/sub-P004_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P004/anat/sub-P004_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P005/anat/sub-P005_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P005/anat/sub-P005_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P006/anat/sub-P006_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P006/anat/sub-P006_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P007/anat/sub-P007_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P007/anat/sub-P007_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P010/anat/sub-P010_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P010/anat/sub-P010_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P011/anat/sub-P011_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P011/anat/sub-P011_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P012/anat/sub-P012_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P012/anat/sub-P012_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P013/anat/sub-P013_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P013/anat/sub-P013_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P014/anat/sub-P014_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P014/anat/sub-P014_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P015/anat/sub-P015_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P015/anat/sub-P015_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P016/anat/sub-P016_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P016/anat/sub-P016_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P017/anat/sub-P017_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P017/anat/sub-P017_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P019/anat/sub-P019_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P019/anat/sub-P019_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P021/anat/sub-P021_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P021/anat/sub-P021_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P022/anat/sub-P022_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P022/anat/sub-P022_UNIT1_lesion-manual2.nii.gz
 create mode 100644 derivatives/labels/sub-P023/anat/sub-P023_UNIT1_lesion-manual2.json
 create mode 100644 derivatives/labels/sub-P023/anat/sub-P0 [...]

2021-12-10 19:32 UTC, merged

2021-12-10 20:46 UTC, jcohenadad commented
thank you @alexfoias 

just for info, when using 'details' you need to have a line in between:
![Screen Shot 2021-12-10 at 3 44 26 PM](https://user-images.githubusercontent.com/2482071/145639063-1fed2a26-2f00-4d0d-8678-4299a40fc15b.png)

otherwise it looks like this:
![Screen Shot 2021-12-10 at 3 44 09 PM](https://user-images.githubusercontent.com/2482071/145639095-e5ac2484-f2df-49e8-856c-2183eeead85a.png)