Add curation script for `INSPIRED` dataset BIDSification
neuropoly/data-management pull request #185
Opened 2022-11-29 15:16 UTC by valosekj

This PR adds a python script for the curation of the `INSPIRED` dataset to be BIDS compliant.
The PR is a draft and is still in progress.

Fixes: #184

2022-11-29 16:02 UTC, jcohenadad reviewed
Please put the script under the dataset, in the 'code/' folder

2022-12-05 14:23 UTC, valosekj commented
I finished the script to be ready for review. Notes below.

## Input dataset

<details><summary>Input dataset (as stored on the `duke/mri/INSPIRED`):</summary>

```
$ tree -L 3
.
├── 01
│   ├── csm
│   │   ├── 001.tar.gz
│   │   ├── 005.tar.gz
│   │   ├── 006.tar.gz
│   │   ├── 007.tar.gz
│   │   ├── 008.tar.gz
│   │   ├── 009.tar.gz
│   │   ├── 010.tar.gz
│   │   ├── 015.tar.gz
│   │   ├── 017.tar.gz
│   │   ├── 018.tar.gz
│   │   ├── 019.tar.gz
│   │   ├── 021.tar.gz
│   │   ├── 022.tar.gz
│   │   └── 023.tar.gz
│   ├── hc
│   │   ├── 001.tar.gz
│   │   ├── 002.tar.gz
│   │   ├── 004.tar.gz
│   │   ├── 005.tar.gz
│   │   ├── 006.tar.gz
│   │   ├── 007.tar.gz
│   │   ├── 009.tar.gz
│   │   ├── 010.tar.gz
│   │   ├── 011.tar.gz
│   │   ├── 012.tar.gz
│   │   ├── 013.tar.gz
│   │   ├── 014.tar.gz
│   │   ├── 015.tar.gz
│   │   └── 016.tar.gz
│   └── sci
│       ├── 003.tar.gz
│       └── 012.tar.gz
├── 02
│   ├── csm
│   │   ├── 001.tar.gz
│   │   ├── 002.tar.gz
│   │   ├── 003.tar.gz
│   │   ├── 004.tar.gz
│   │   ├── 005.tar.gz
│   │   ├── 006.tar.gz
│   │   ├── 007.tar.gz
│   │   ├── 008.tar.gz
│   │   ├── 009.tar.gz
│   │   ├── 010.tar.gz
│   │   ├── 011.tar.gz
│   │   ├── 012.tar.gz
│   │   ├── 013.tar.gz
│   │   ├── 014.tar.gz
│   │   ├── 015.tar.gz
│   │   ├── 016.tar.gz
│   │   ├── 017.tar.gz
│   │   ├── 018.tar.gz
│   │   ├── 019.tar.gz
│   │   ├── 020.tar.gz
│   │   ├── 021.tar.gz
│   │   ├── 022.tar.gz
│   │   ├── 023.tar.gz
│   │   └── 024.tar.gz
│   ├── hc
│   │   ├── 001.tar.gz
│   │   ├── 002.tar.gz
│   │   ├── 003.tar.gz
│   │   ├── 004.tar.gz
│   │   ├── 005.tar.gz
│   │   ├── 006.tar.gz
│   │   ├── 007.tar.gz
│   │   ├── 008.tar.gz
│   │   ├── 009.tar.gz
│   │   └── 010.tar.gz
│   └── sci
│       ├── 001.tar.gz
│       ├── 002.tar.gz
│       ├── 003.tar.gz
│       ├── 004.tar.gz
│       ├── 005.tar.gz
│       ├── 006.tar.gz
│       ├── 007.tar.gz
│       ├── 008.tar.gz
│       ├── 010.tar.gz
│       ├── 011.tar.gz
│       ├── 012.tar.gz
│       ├── 013.tar.gz
│       ├── 014.tar.gz
│       ├── 015.tar.gz
│       ├── 016.tar.gz
│       └── 017.tar.gz
└── README.txt
```
</details>

<details><summary>Files for a single subject (after unpacking by `tar -xf`):</summary>

```
/01/csm/001$ tree -L 5
.
└── bl
    ├── brain
    │   ├── dwi.bval
    │   ├── dwi.bvec
    │   ├── dwi.nii.gz
    │   ├── dwi_ad1000.nii.gz
    │   ├── dwi_md1000.nii.gz
    │   ├── dwi_rd1000.nii.gz
    │   ├── dwi_reversed_blip.nii.gz
    │   ├── mpm_A.nii.gz
    │   ├── mpm_MT.nii.gz
    │   ├── mpm_MT_std.nii.gz
    │   ├── mpm_MT_std_Cerebellum.nii.gz
    │   ├── mpm_MT_std_NeuroMorph_BiasCorrected.nii.gz
    │   ├── mpm_MT_std_NeuroMorph_Brain.nii.gz
    │   ├── mpm_MT_std_NeuroMorph_Parcellation.nii.gz
    │   ├── mpm_MT_std_NeuroMorph_Segmentation.nii.gz
    │   ├── mpm_MT_std_NeuroMorph_Segmentation_clean.nii.gz
    │   ├── mpm_MT_std_NeuroMorph_Segmentation_flat.nii.gz
    │   ├── mpm_MT_std_NeuroMorph_TIV.nii.gz
    │   ├── mpm_MT_std_NeuroMorph_prior.nii.gz
    │   ├── mpm_R1_UNICORT.nii.gz
    │   ├── mpm_R2s_OLS.nii.gz
    │   └── mpm_raw
    │       ├── sINSPIREDTrial-0002-00001-000176-01.json
    │       ├── sINSPIREDTrial-0002-00001-000176-01.nii
    │       ├── sINSPIREDTrial-0002-00001-000352-02.json
    │       ├── sINSPIREDTrial-0002-00001-000352-02.nii
    │       ├── sINSPIREDTrial-0002-00001-000528-03.json
    │       ├── sINSPIREDTrial-0002-00001-000528-03.nii
    │       ├── sINSPIREDTrial-0002-00001-000704-04.json
    │       ├── sINSPIREDTrial-0002-00001-000704-04.nii
    │       ├── sINSPIREDTrial-0002-00001-000880-05.json
    │       ├── sINSPIREDTrial-0002-00001-000880-05.nii
    │       ├── sINSPIREDTrial-0002-00001-001056-06.json
    │       ├── sINSPIREDTrial-0002-00001-001056-06.nii
    │       ├── sINSPIREDTrial-0005-00001-000176-01.json
    │       ├── sINSPIREDTrial-0005-00001-000176-01.nii
    │       ├── sINSPIREDTrial-0005-00001-000352-02.json
    │       ├── sINSPIREDTrial-0005-00001-000352-02.nii
    │       ├── sINSPIREDTrial-0005-00001-000528-03.json
    │       ├── sINSPIREDTrial-0005-00001-000528-03.nii
    │       ├── sINSPIREDTrial-0005-00001-000704-04.json
    │       ├── sINSPIREDTrial-0005-00001-000704-04.nii
    │       ├── sINSPIREDTrial-0005-00001-000880-05.json
    │       ├── sINSPIREDTrial-0005-00001-000880-05.nii
    │       ├── sINSPIREDTrial-0005-00001-001056-06.json
    │       ├── sINSPIREDTrial-0005-00001-001056-06.nii
    │       ├── sINSPIREDTrial-0005-00001-001232-07.json
    │       ├── sINSPIREDTrial-0005-00001-001232-07.nii
    │       ├── sINSPIREDTrial-0005-00001-001408-08.json
    │       ├── sINSPIREDTrial-0005-00001-001408-08.nii
    │       ├── sINSPIREDTrial-0008-00001-000176-01.json
    │       ├── sINSPIREDTrial-0008-00001-000176-01.nii
    │       ├── sINSPIREDTrial-0008-00001-000352-02.json
    │       ├── sINSPIREDTrial-0008-00001-000352-02.nii
    │       ├── sINSPIREDTrial-0008-00001-000528-03.json
    │       ├── sINSPIREDTrial-0008-00001-000528-03.nii
    │       ├── sINSPIREDTrial-0008-00001-000704-04.json
    │       ├── sINSPIREDTrial-0008-00001-000704-04.nii
    │       ├── sINSPIREDTrial-0008-00001-000880-05.json
    │       ├── sINSPIREDTrial-0008-00001-000880-05.nii
    │       ├── sINSPIREDTrial-0008-00001-001056-06.json
    │       ├── sINSPIREDTrial-0008-00001-001056-06.nii
    │       ├── sINSPIREDTrial-0008-00001-001232-07.json
    │       ├── sINSPIREDTrial-0008-00001-001232-07.nii
    │       ├── sINSPIREDTrial-0008-00001-001408-08.json
    │       └── sINSPIREDTrial-0008-00001-001408-08.nii
    └── cord
        ├── dwi.bval
        ├── dwi.bvec
        ├── dwi.nii.gz
        ├── dwi_reversed_blip.nii.gz
        ├── pd_medic.nii.gz
        ├── sct_processing
        │   ├── dwi
        │   │   ├── dti_AD.nii.gz
        │   │   ├── dti_FA.nii.gz
        │   │   ├── dti_MD.nii.gz
        │   │   └── dti_RD.nii.gz
        │   ├── t2
        │   │   └── t2_seg.nii.gz
        │   └── t2s
        │       ├── gm_seg.nii.gz
        │       └── wm_seg.nii.gz
        ├── t1_sag.nii.gz
        ├── t2_sag.nii.gz
        └── t2_tra.nii.gz
```
</details>

## Conversion notes

So far, for the `cord` folder, I am converting all raw images (i.e. I am not converting files in the `cord/sct_processing`). 
For the `brain` folder, I am converting DWI files and raw MPM images in the `brain/mpm_raw` folder (i.e., I am not converting processed `mpm_` files).
To differentiate spine imaging from the brain, I am using the `bp-cspine` tag.

The filename conversion dictionaries are listed on [lines 47-67](https://github.com/neuropoly/data-management/blob/ad2e6585060098b12c6ef23eebd257e584a3c694/scripts/curate_data_inspired.py#L47-L67).

The tricky part was related to the MPM. I had to load json sidecar for each MPM file to fetch `EchoTime`, `FlipAngle`, and `SeriesDescription`. Then the BIDS complaint MPM filenames are constructed within the `construct_mpm_bids_filename` function:

https://github.com/neuropoly/data-management/blob/ad2e6585060098b12c6ef23eebd257e584a3c694/scripts/curate_data_inspired.py#L118-L120

## Output dataset

I was testing the script on the copy of the dataset (`extrassd1/janvalosek/INSPIRED`). The converted dataset is available in `extrassd1/janvalosek/INSPIRED_bids`. 

The script also creates `participants.tsv`, `participants.json`, `dataset_description.json`, and `README` files. Also, the script copies itself to the `/code` folder.

<details><summary>Output dataset (the first subject shown):</summary>

```
$ tree -L 3
.
├── bids_conversion.log
├── code
│   └── curate_data_inspired.py
├── dataset_description.json
├── participants.json
├── participants.tsv
├── README
├── sub-torontoDCM001
│   ├── anat
│   │   ├── sub-torontoDCM001_acq-axial_bp-cspine_T2w.json
│   │   ├── sub-torontoDCM001_acq-axial_bp-cspine_T2w.nii.gz
│   │   ├── sub-torontoDCM001_acq-coronal_bp-cspine_T2w.json
│   │   ├── sub-torontoDCM001_acq-coronal_bp-cspine_T2w.nii.gz
│   │   ├── sub-torontoDCM001_ac [...]

2022-12-05 14:24 UTC, valosekj commented
> Please put the script under the dataset, in the 'code/' folder

Done here:

https://github.com/neuropoly/data-management/blob/31df28ef8fe2c45059aee2fc1d8cde4e5166b53d/scripts/curate_data_inspired.py#L245-L250

2022-12-06 16:46 UTC, jcohenadad requested changes
- Please keep the original subject ID
- Update README (see my other comment in this section)

2022-12-06 16:57 UTC, jcohenadad commented on scripts/curate_data_inspired.py
> +        logger.info(f'README created in {path_output}')
impossble to properly review-- because of formatting-- better approach : just put readme int he pR and i reveiw it---

2022-12-06 16:57 UTC, jcohenadad commented
julien todo: fix readme and jan: ping julien for readme

2022-12-06 16:58 UTC, jcohenadad commented
does it pass the BIDS validator?

2022-12-12 20:24 UTC, valosekj commented
> does it pass the BIDS validator?

No, it doesn't. It seems that `bp-cspine` tag is problematic. `bp` tag has been proposed by [BIDS Extension Proposal 25 (BEP025)](https://docs.google.com/document/d/1chZv7vAPE-ebPDxMktfI9i1OkLNR2FELIfpVYsaZPr4/edit#heading=h.4k1noo90gelw) which [seems not to be merged yet](https://bids.neuroimaging.io/get_involved.html#extending-the-bids-specification). 
Thus, I included files containing `bp-cspine` tag to the `.bidsignore` file (as also done in [courtois-neuromod](https://github.com/courtois-neuromod/anat/blob/main/.bidsignore))

2022-12-12 20:24 UTC, valosekj commented
Sorry, accidentally closed --> reopening.

2022-12-12 20:28 UTC, valosekj commented
> * Please keep the original subject ID

Done in https://github.com/neuropoly/data-management/pull/185/commits/09e12eddafe213b5a3bf1c7dd1ea6abdbcba49e5

> * Update README (see my other comment in this section)

README is now provided right within this PR, see [here](https://github.com/neuropoly/data-management/pull/185/commits/8556af9bacf8e137ec2cc2675ebef9634df25fe3)

2022-12-12 20:31 UTC, valosekj commented
> does it pass the BIDS validator?

No, it doesn't. It seems that `bp-cspine` tag is problematic. `bp` tag has been proposed by [BIDS Extension Proposal 25 (BEP025)](https://docs.google.com/document/d/1chZv7vAPE-ebPDxMktfI9i1OkLNR2FELIfpVYsaZPr4/edit#heading=h.4k1noo90gelw) which [seems not to be merged yet](https://bids.neuroimaging.io/get_involved.html#extending-the-bids-specification). 
Thus, I included files containing `bp-cspine` tag to the `.bidsignore` file (as also done in [courtois-neuromod](https://github.com/courtois-neuromod/anat/blob/main/.bidsignore)).

2022-12-12 20:48 UTC, jcohenadad commented
> No, it doesn't. It seems that bp-cspine tag is problematic. bp tag has been proposed by [BIDS Extension Proposal 25 (BEP025)](https://docs.google.com/document/d/1chZv7vAPE-ebPDxMktfI9i1OkLNR2FELIfpVYsaZPr4/edit#heading=h.4k1noo90gelw) which [seems not to be merged yet](https://bids.neuroimaging.io/get_involved.html#extending-the-bids-specification).
Thus, I included files containing bp-cspine tag to the .bidsignore file (as also done in [courtois-neuromod](https://github.com/courtois-neuromod/anat/blob/main/.bidsignore)):

I'm still unsure if the strategy adopted for cneuromod is the best, given that the BEP25 has been around for more than 3y now, and I'm unsure when it will be official. There is [comment](https://docs.google.com/document/d/1xeiFACAnK_X64kL6XoXo8vpZ9Bn6B5Xd3j59Le1clRE/edit#) from @mariehbourget about the suggestion made in the [BEP31](https://docs.google.com/document/d/1Nlu6QVQrbOQtdtcRarsONbX5SrOubXWBvkV37LRRqrc/edit#heading=h.4k5zzopnsbd9), which is that for now, we should/can use the `acq-` field to specify BodyPart (it is BIDS-compatible), and once/if BEP25 is in, then we can switch to bp-

2022-12-12 21:04 UTC, valosekj commented
> There is [comment](https://docs.google.com/document/d/1xeiFACAnK_X64kL6XoXo8vpZ9Bn6B5Xd3j59Le1clRE/edit#) from @mariehbourget about the suggestion made in the [BEP31](https://docs.google.com/document/d/1Nlu6QVQrbOQtdtcRarsONbX5SrOubXWBvkV37LRRqrc/edit#heading=h.4k5zzopnsbd9), which is that for now, we should/can use the `acq-` field to specify BodyPart (it is BIDS-compatible), and once/if BEP25 is in, then we can switch to bp-

There is a thing that `acq-` field is already used (we have `acq-axial` and `acq-coronal` for T2w and `acq-MTw`, `acq-PDw`, and `acq-T1w` for MPM):

```
$ tree -L 3
.
├── sub-torontoDCM001
│   ├── anat
│   │   ├── sub-torontoDCM001_acq-axial_bp-cspine_T2w.json
│   │   ├── sub-torontoDCM001_acq-axial_bp-cspine_T2w.nii.gz
│   │   ├── sub-torontoDCM001_acq-coronal_bp-cspine_T2w.json
│   │   ├── sub-torontoDCM001_acq-coronal_bp-cspine_T2w.nii.gz
│   │   ├── sub-torontoDCM001_acq-MTw_echo-1_flip-1_mt-on_MPM.json
│   │   ├── sub-torontoDCM001_acq-MTw_echo-1_flip-1_mt-on_MPM.nii.gz
...
│   │   ├── sub-torontoDCM001_acq-PDw_echo-1_flip-2_mt-off_MPM.nii.gz
│   │   ├── sub-torontoDCM001_acq-PDw_echo-2_flip-2_mt-off_MPM.json
...
│   │   ├── sub-torontoDCM001_acq-T1w_echo-1_flip-3_mt-off_MPM.json
│   │   ├── sub-torontoDCM001_acq-T1w_echo-1_flip-3_mt-off_MPM.nii.gz
...
```

2022-12-12 21:17 UTC, jcohenadad commented
> There is a thing that acq- field is already used (we have acq-axial and acq-coronal for T2w and acq-MTw, acq-PDw, and acq-T1w for MPM):

this is a very good point. So maybe we should use `bp-` indeed 🤷

2022-12-12 22:18 UTC, mariehbourget commented
> > There is a thing that acq- field is already used (we have acq-axial and acq-coronal for T2w and acq-MTw, acq-PDw, and acq-T1w for MPM):
> 
> this is a very good point. So maybe we should use `bp-` indeed 🤷

If you absolutely need BIDS compliant filenames, an alternative would be to combine both information in the `acq-` entity in `camelCase`.
examples:
`acq-axialCspine` or `acq-cspineAxial` for T2w
and
`acq-PDwCspine` or `acq-cspinePDw` for MPM
A description of each labels could also be added to the README to clarify the labeling.

2022-12-13 14:43 UTC, jcohenadad commented
https://github.com/neuropoly/data-management/pull/185#issuecomment-1347421696 this is a good option as well

2022-12-21 20:41 UTC, valosekj commented
Thank you @mariehbourget!

I switched to `acq-cspineSagittal` and `acq-cspineAxial` in https://github.com/neuropoly/data-management/pull/185/commits/30ae9979329ec2fc261abf8be9c5857636af063a

2023-01-21 15:22 UTC, valosekj commented
@jcohenadad, I updated the [script](https://github.com/neuropoly/data-management/blob/jv/curate_inspired/scripts/curate_data_inspired.py) for INSPIRED dataset BIDSification. The dataset should be ready for upload to git-annex.

[README.md](https://github.com/neuropoly/data-management/blob/jv/curate_inspired/scripts/README.md) is attached to this PR for easy review.

The BIDSified dataset is available in: `~/extrassd1/janvalosek/INSPIRED_bids_20230121`. It passes `bids-validator`.

Based on [our recent discussion](https://github.com/neuropoly/data-management/issues/195#issuecomment-1369202235), I'm using `label-xx_seg.nii.gz` suffixes for SC, WM, and GM segmentations:

https://github.com/neuropoly/data-management/blob/33f440a17047d77665e0c0206e598b9499099860/scripts/curate_data_inspired.py#L67-L70

`acq-cspine` tag in combination with `camelCase` is used to differentiate spine images from the brain. Details [here](https://github.com/neuropoly/data-management/pull/185#issuecomment-1362069079).

---

TODO: Once the dataset is git-annexed, I will add clinical info (mJOA, etc.) and manual disc labels (which I created in the context of the OHBM abstract) as separate commits to allow easy tracking by `git log --stat git-annex`.

2023-01-24 16:06 UTC, jcohenadad commented on scripts/README.md
> +This is an MRI dataset acquired in the context of the INSPIRED project.
```suggestion
This is an MRI dataset acquired in the context of the INSPIRED project (https://www.spinalsurgerynews.com/2016/10/inspired-spinal-cord-neuro-imaging-project/14594).
```

2023-01-24 16:07 UTC, jcohenadad commented on scripts/README.md
> +https://www.spinalsurgerynews.com/2016/10/inspired-spinal-cord-neuro-imaging-project/14594
```suggestion
## Contact Person

Main PI of the project: Claudia Wheeler Kingshott
Contact person: Julien Cohen-Adad
```

2023-02-15 23:30 UTC, valosekj commented
BIDSification completed (see https://github.com/neuropoly/data-management/issues/208) --> closing

2023-02-15 23:30 UTC, closed without merging